# Library and Tools

In [1]:
import yaml
from src.utils import load_data, split_input_output, split_train_test, serialize_data, deserialize_data

# Constant Variables

In [2]:
with open('../config/path.yaml', 'r') as f:
    path = yaml.safe_load(f)

X_train_path = path['data_path']['input']['X_train']
x_test_path = path['data_path']['input']['x_test']
x_valid_path = path['data_path']['input']['x_valid']
y_train_path = path['data_path']['output']['y_train']
y_test_path = path['data_path']['output']['y_test']
y_valid_path = path['data_path']['output']['y_valid']
fname = path['data_path']['data']['raw']['credit_risk']

In [3]:
FNAME = fname
TARGET_COL = "loan_status"
X_TRAIN_PATH = X_train_path
X_TEST_PATH = x_test_path
X_VALID_PATH = x_valid_path
Y_TRAIN_PATH = y_train_path
Y_TEST_PATH = y_test_path
Y_VALID_PATH = y_valid_path

# Playground

In [4]:
data = load_data(FNAME)
data.head(10)

File exist and is readable
Data Shape : (32581, 12)

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length
0,22,59000,RENT,123.0,PERSONAL,D,35000,16.02,1,0.59,Y,3
1,21,9600,OWN,5.0,EDUCATION,B,1000,11.14,0,0.10,N,2
2,25,9600,MORTGAGE,1.0,MEDICAL,C,5500,12.87,1,0.57,N,3
3,23,65500,RENT,4.0,MEDICAL,C,35000,15.23,1,0.53,N,2
4,24,54400,RENT,8.0,MEDICAL,C,35000,14.27,1,0.55,Y,4
5,21,9900,OWN,2.0,VENTURE,A,2500,7.14,1,0.25,N,2
6,26,77100,RENT,8.0,EDUCATION,B,35000,12.42,1,0.45,N,3
7,24,78956,RENT,5.0,MEDICAL,B,35000,11.11,1,0.44,N,4
8,24,83000,RENT,8.0,PERSONAL,A,35000,8.90,1,0.42,N,2
9,21,10000,OWN,6.0,VENTURE,D,1600,14.74,1,0.16,N,3

In [5]:
X,y = split_input_output(data, target_col= TARGET_COL)

Original data shape: (32581, 12)
X data shape: (32581, 11)
y data shape: (32581,)

In [6]:
X.head(5)

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length
0,22,59000,RENT,123.0,PERSONAL,D,35000,16.02,0.59,Y,3
1,21,9600,OWN,5.0,EDUCATION,B,1000,11.14,0.10,N,2
2,25,9600,MORTGAGE,1.0,MEDICAL,C,5500,12.87,0.57,N,3
3,23,65500,RENT,4.0,MEDICAL,C,35000,15.23,0.53,N,2
4,24,54400,RENT,8.0,MEDICAL,C,35000,14.27,0.55,Y,4

In [7]:
y.head(5)

0    1
1    0
2    1
3    1
4    1
Name: loan_status, dtype: int64

In [8]:
X_train, X_non_train, y_train, y_non_train = split_train_test(X, y, test_size= 0.2, random_state= 42)
X_valid, X_test, y_valid, y_test = split_train_test(X_non_train, y_non_train, test_size= 0.5, random_state= 42)

X train shape: (26064, 11)
X test shape: (6517, 11)
y train shape: (26064,)
y test shape: (6517,)
X train shape: (3258, 11)
X test shape: (3259, 11)
y train shape: (3258,)
y test shape: (3259,)

In [9]:
# Serialize data
serialize_data(X_train, X_TRAIN_PATH)
serialize_data(X_test, X_TEST_PATH)
serialize_data(X_valid, X_VALID_PATH)
serialize_data(y_train, Y_TRAIN_PATH)
serialize_data(y_test, Y_TEST_PATH)
serialize_data(y_valid, Y_VALID_PATH)

Succeed to serialize data
Succeed to serialize data
Succeed to serialize data
Succeed to serialize data
Succeed to serialize data
Succeed to serialize data

In [10]:
# Testing deserialize function
X_des_train = deserialize_data(X_TEST_PATH)
X_des_train.head(5)

Succeed to deserialize data

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length
20439,30,31000,RENT,7.0,MEDICAL,D,4750,14.84,0.15,N,9
30809,36,60000,RENT,3.0,EDUCATION,A,9500,7.14,0.16,N,12
22978,29,33000,RENT,5.0,HOMEIMPROVEMENT,A,8000,5.79,0.24,N,8
19435,27,40000,RENT,3.0,PERSONAL,A,3000,7.05,0.07,N,8
31011,39,56000,RENT,16.0,DEBTCONSOLIDATION,C,10000,13.06,0.18,N,11

In [11]:
X_des_train.shape

(3259, 11)