# Library and Tools

In [1]:
import os
import pandas as pd
import joblib
import yaml
import pathlib
from sklearn.model_selection import train_test_split

# Constant Variables

In [2]:
with open('../config/path.yaml', 'r') as f:
    path = yaml.safe_load(f)

X_train_path = path['data_path']['input']['X_train']
x_test_path = path['data_path']['input']['x_test']
x_valid_path = path['data_path']['input']['x_valid']
y_train_path = path['data_path']['output']['y_train']
y_test_path = path['data_path']['output']['y_test']
y_valid_path = path['data_path']['output']['y_valid']
fname = path['data_path']['data']['raw']['credit_risk']

In [3]:
FNAME = fname
TARGET_COL = "loan_status"
X_TRAIN_PATH = X_train_path
X_TEST_PATH = x_test_path
X_VALID_PATH = x_valid_path
Y_TRAIN_PATH = y_train_path
Y_TEST_PATH = y_test_path
Y_VALID_PATH = y_valid_path

# Functions

In [4]:
def load_data(fname: str):
    """
    To load data from desired path

    Paramaters :
        - fname : File path

    Return value:
        - data : Data wrapped in pandas dataframe
    """

    try:
        with open(fname, 'r'):
            pass
        print("File exist and is readable")
    
    except FileNotFoundError:
        print("File doesn't exist")
    
    except PermissionError:
        print("File exists but no permission to access")

    if fname.endswith('.csv'):
        data = pd.read_csv(fname)
        print(f"Data Shape : {data.shape}")

    elif fname.endswith('.xlsx'):
        data = pd.read_excel(fname)
        print(f"Data Shape : {data.shape}")
    
    else :
        data = pd.DataFrame()
        print("Can't read from others type of file, data will set into empty dataframe")
    
    return data

def split_input_output(data: pd.DataFrame, target_col: str):
    """ 
    Splitting input and output from data 

    Parameters:
        - data: Pandas dataframe
        - target_col: string

    Return Value:
        - X : Input in pandas dataframe
        - y : Output in pandas dataframe
    """

    X = data.drop(columns= target_col)
    y = data[target_col]

    print(f"Original data shape: {data.shape}")
    print(f"X data shape: {X.shape}")
    print(f"y data shape: {y.shape}")

    return X, y

def split_train_test(X: pd.DataFrame, y: pd.DataFrame, test_size: float, random_state: int):
    """
    Splitting between train and test data

    Parameters:
        - X : Data as an input in pandas dataframe
        - y : Data as an output in pandas dataframe
        - test_size : Propotion of test data, if you set 0.2 then train data will have 0.8 of the data and the type is float
        - random_state : Random number generator to shuffle the data and the type is integer

    Return Value: 
        - X_train : Data for input train in pandas dataframe
        - X_test : Data for input test in pandas dataframe
        - y_train : Data for output train in pandas dataframe
        - y_test : Data for output test in pandas dataframe
    """

    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= test_size, random_state= random_state, stratify= y)
    print(f"X train shape: {X_train.shape}")
    print(f"X test shape: {X_test.shape}")
    print(f"y train shape: {y_train.shape}")
    print(f"y test shape: {y_test.shape}")

    return X_train, X_test, y_train, y_test

def serialize_data(data: pd.DataFrame, path: str):
    """
    Serialize data into pickle file

    Parameters:
        - data : Data in pandas dataframe format
        - path : Path used to save serialize data in string

    Return Value:
        None, serialize data will automatically saved into configured path
    """

    try: 
        joblib.dump(data, path)
        print("Succeed to serialize data")
    except:
        print("Failed to serialize data!")

def deserialize_data(path: str):
    """
    Desrialize data from existing file

    Parameters:
        - path : Path used to load serializedata in string

    Return Value:
        - data : contains deserialize data in pandas dataframe
    """

    try:
        data = joblib.load(path)
        print("Succeed to deserialize data")
    except:
        print("Failed to deserialize data!")

    return data

# Playground

In [5]:
data = load_data(FNAME)
data.head(10)

File exist and is readable
Data Shape : (32581, 12)

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length
0,22,59000,RENT,123.0,PERSONAL,D,35000,16.02,1,0.59,Y,3
1,21,9600,OWN,5.0,EDUCATION,B,1000,11.14,0,0.10,N,2
2,25,9600,MORTGAGE,1.0,MEDICAL,C,5500,12.87,1,0.57,N,3
3,23,65500,RENT,4.0,MEDICAL,C,35000,15.23,1,0.53,N,2
4,24,54400,RENT,8.0,MEDICAL,C,35000,14.27,1,0.55,Y,4
5,21,9900,OWN,2.0,VENTURE,A,2500,7.14,1,0.25,N,2
6,26,77100,RENT,8.0,EDUCATION,B,35000,12.42,1,0.45,N,3
7,24,78956,RENT,5.0,MEDICAL,B,35000,11.11,1,0.44,N,4
8,24,83000,RENT,8.0,PERSONAL,A,35000,8.90,1,0.42,N,2
9,21,10000,OWN,6.0,VENTURE,D,1600,14.74,1,0.16,N,3

In [14]:
data.dtypes

person_age                      int64
person_income                   int64
person_home_ownership          object
person_emp_length             float64
loan_intent                    object
loan_grade                     object
loan_amnt                       int64
loan_int_rate                 float64
loan_status                     int64
loan_percent_income           float64
cb_person_default_on_file      object
cb_person_cred_hist_length      int64
dtype: object

In [6]:
X,y = split_input_output(data, target_col= TARGET_COL)

Original data shape: (32581, 12)
X data shape: (32581, 11)
y data shape: (32581,)

In [7]:
X.head(5)

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length
0,22,59000,RENT,123.0,PERSONAL,D,35000,16.02,0.59,Y,3
1,21,9600,OWN,5.0,EDUCATION,B,1000,11.14,0.10,N,2
2,25,9600,MORTGAGE,1.0,MEDICAL,C,5500,12.87,0.57,N,3
3,23,65500,RENT,4.0,MEDICAL,C,35000,15.23,0.53,N,2
4,24,54400,RENT,8.0,MEDICAL,C,35000,14.27,0.55,Y,4

In [8]:
y.head(5)

0    1
1    0
2    1
3    1
4    1
Name: loan_status, dtype: int64

In [9]:
X_train, X_non_train, y_train, y_non_train = split_train_test(X, y, test_size= 0.2, random_state= 42)
X_valid, X_test, y_valid, y_test = split_train_test(X_non_train, y_non_train, test_size= 0.5, random_state= 42)

X train shape: (26064, 11)
X test shape: (6517, 11)
y train shape: (26064,)
y test shape: (6517,)
X train shape: (3258, 11)
X test shape: (3259, 11)
y train shape: (3258,)
y test shape: (3259,)

In [10]:
# Serialize data
serialize_data(X_train, X_TRAIN_PATH)
serialize_data(X_test, X_TEST_PATH)
serialize_data(X_valid, X_VALID_PATH)
serialize_data(y_train, Y_TRAIN_PATH)
serialize_data(y_test, Y_TEST_PATH)
serialize_data(y_valid, Y_VALID_PATH)

Succeed to serialize data
Succeed to serialize data
Succeed to serialize data
Succeed to serialize data
Succeed to serialize data
Succeed to serialize data

In [11]:
# Testing deserialize function
X_des_train = deserialize_data(X_TRAIN_PATH)
X_des_train.head(5)

Succeed to deserialize data

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length
15884,25,241875,MORTGAGE,4.0,EDUCATION,A,16000,7.05,0.07,N,4
15138,21,18000,RENT,5.0,PERSONAL,B,1500,12.18,0.08,N,4
7474,25,53000,MORTGAGE,10.0,MEDICAL,B,16000,12.53,0.30,N,2
18212,28,16800,OWN,NaN,MEDICAL,C,5000,13.98,0.30,N,8
6493,25,50000,MORTGAGE,2.0,VENTURE,A,10000,7.90,0.20,N,2